### ISSUE TITLE
inquire

### ISSUE THREAD

**Issue by nongojames1** [Mugerwa-Joseph/hospital-management#2]
How do we open up this project on our local computers?

**Comment by nongojames1** [comment]
Thanks for the service.

**Comment by Mugerwa-Joseph** [comment]
Thanks James for raising up this Issue.

For you to have this project running on your local machine,
 You need the following:
1-A local server, this might be WAMP or XAMP if you are on a windows platform, if you are  on MAC, Mamp,
2-You need a database running in your local server., for the database script, check in the database folder in the project.
3- Create the database on your server and then just import the script into your database.

Then copy the project and paste it to your public folder of the server, This is either www in wamp on your major hard disk, or htdocs in xamp on your major hard disk.

Then you can access the project from the browser.
